### ISSUE TITLE
Build HDFS location -> distributed byte Futures function

### ISSUE THREAD

**Issue by koverholt** [blaze/hdfs3#11]

**Comment by mrocklin** [comment]
My intent behind this issue was to produce `distributed.Future` objects for every block of bytes in an HDFS file.  From here we can do most things, map various in-memory read functions (`pd.read_csv`, `avro.load`, etc..) on these bytes with distributed.  This work will probably happen within the `distributed` library.

**Comment by mrocklin** [comment]
We have an accurate HDFS path -> distributed byte Futures function now.  I'd like to extend this to support lazy evaluation with `dask.Value` objects.  Keeping this issue alive until then.

**Comment by martindurant** [comment]
Should close now?
